"""`eifctl doctor` - wraps _impl.eif_verify_runtime.main(), plus one
package-specific check the shared script has no reason to know about:
does this installed package's OWN current provenance still match what an
installed-package-sourced instance last recorded? The shared script only
validates the lock's internal consistency; only the wrapper knows whether
it's currently a different version/resource-bundle than that instance was
generated from.
"""
from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

import yaml

from .._impl import eif_verify_runtime
from ..resources import framework_root
from ..workspace_materialization import verify_workspace_materialization
from .init_cmd import DISTRIBUTION_NAME, _resource_manifest_digest


def _instance_path_from_argv(argv: list[str]) -> Path:
    if "--instance-path" in argv:
        return Path(argv[argv.index("--instance-path") + 1]).resolve()
    return Path(".").resolve()


def _check_installed_package_consistency(instance_path: Path, resources_root: Path) -> list[str]:
    lock_path = instance_path / ".eif" / "framework.lock.yaml"
    if not lock_path.exists():
        return []  # the shared script already reports a missing/invalid lock
    try:
        lock = yaml.safe_load(lock_path.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return []  # the shared script already reports invalid YAML
    if not isinstance(lock, dict):
        return []
    framework = lock.get("framework") or {}
    if framework.get("source_type") != "installed-package":
        return []  # this instance was not generated by an installed package - nothing to compare
    package = lock.get("package") or {}

    problems = []
    try:
        running_version = metadata.version(DISTRIBUTION_NAME)
    except metadata.PackageNotFoundError:
        running_version = None
    recorded_version = package.get("version")
    if running_version is not None and recorded_version is not None and running_version != recorded_version:
        problems.append(
            f"this instance was generated by {DISTRIBUTION_NAME} {recorded_version}, "
            f"but the currently running eifctl is {running_version} - re-run `eifctl init` "
            f"(a routine upgrade) to refresh provenance for the version actually installed now."
        )

    recorded_digest = package.get("resource_manifest_digest")
    if recorded_digest is not None:
        current_digest = _resource_manifest_digest(resources_root)
        if current_digest != recorded_digest:
            problems.append(
                f"the currently installed {DISTRIBUTION_NAME} package's bundled resources/ "
                f"tree does not match its own recorded digest ({recorded_digest}, now "
                f"{current_digest}) - the installed package may be corrupted or its files "
                f"hand-modified in site-packages. Reinstall the package."
            )
    return problems


DEFER_WORKSPACE_FLAG = "--defer-workspace-check"


def run(argv: list[str]) -> int:
    # `eifctl projects upgrade` runs the framework axis first and the
    # workspace axis immediately after, in one coordinated pass. Without this
    # flag, pre-existing workspace drift failed the framework axis's
    # post-upgrade doctor, was reported as `axis=framework` (the wrong axis),
    # and blocked the very step that would have repaired it.
    defer_workspace = DEFER_WORKSPACE_FLAG in argv
    argv = [item for item in argv if item != DEFER_WORKSPACE_FLAG]
    with framework_root() as root:
        full_argv = ["--framework-root", str(root), *argv]
        rc = eif_verify_runtime.main(full_argv)

        instance_path = _instance_path_from_argv(argv)
        problems = _check_installed_package_consistency(instance_path, root)
        if not defer_workspace:
            problems += verify_workspace_materialization(instance_path)
        for problem in problems:
            print(f"eifctl doctor: FAIL {problem}", file=sys.stderr)
        if problems:
            rc = 1
        # The wrapped script prints its own "all checks passed" banner before
        # these wrapper-level checks have run, so on failure that banner was
        # the last line a user saw while the command exited non-zero. This
        # line is the authoritative verdict for the command as a whole.
        if rc == 0:
            print(f"eifctl doctor: PASS {instance_path}")
        else:
            print(f"eifctl doctor: FAILED {instance_path} - see the checks above")
        return rc
