#!/usr/bin/env python3
"""Regressions from upgrading real connected projects with the published
0.2.3 wheel: the two guards in `eifctl upgrade` that stopped or misdescribed
an upgrade that was fine.

Both were found by running the command, not by reading it.

Usage:
    python scripts/tests/test_upgrade_guards.py
"""
from __future__ import annotations

import hashlib
import io
import contextlib
import sys
import tempfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import eif_verify_runtime as verify  # noqa: E402
from engineering_intelligence_framework import cli  # noqa: E402
from engineering_intelligence_framework.commands import init_cmd, upgrade  # noqa: E402
from workspace_test_support import commit_all, git  # noqa: E402


def check(name: str, condition: bool, detail: str = "") -> tuple[bool, str]:
    condition = bool(condition)
    return (
        condition,
        f"{'PASS' if condition else 'FAIL'} {name}"
        + (f": {detail}" if detail and not condition else ""),
    )


def make_project(root: Path, name: str) -> Path:
    project = root / name
    knowledge = project / "knowledge"
    knowledge.mkdir(parents=True)
    (knowledge / "fact.md").write_bytes(
        b"---\ntype: fact\nstatus: validated\nscope: project\n"
        b"created: 2026-07-29\nreview_after: 2026-10-29\n---\n\n# Fact\n\nA fact.\n"
    )
    git(project, "init", "-b", "main", "-q")
    rc = cli.main(["init", str(project), "--adapter", "claude-code"])
    if rc != 0:
        raise RuntimeError(f"init failed for {name}")
    commit_all(project, "bootstrap")
    return project


def drift_the_index(project: Path) -> None:
    """Exactly what happened: the index was regenerated by hand, so its bytes
    no longer match the sha256 the lock recorded when eif_init wrote it."""
    lock = yaml.safe_load((project / ".eif" / "framework.lock.yaml").read_text(encoding="utf-8"))
    index = project / lock["knowledge_index"]["path"]
    index.write_bytes(index.read_bytes() + b"\n<!-- regenerated by hand -->\n")


def index_matches_lock(project: Path) -> bool:
    lock = yaml.safe_load((project / ".eif" / "framework.lock.yaml").read_text(encoding="utf-8"))
    recorded = lock["knowledge_index"]
    actual = (project / recorded["path"]).read_bytes()
    return hashlib.sha256(actual).hexdigest() == recorded["sha256"]


def check_pre_upgrade_defers_regenerated_state(root: Path) -> list[tuple[bool, str]]:
    """The pre-flight run inside `eifctl upgrade` exists to refuse an upgrade
    on top of a runtime bundle it cannot attest to. A drifted knowledge index
    is not that: the refresh rewrites the index and the lock hash together, so
    failing here blocked the one command that repairs it and pointed at
    eif_init.py, which is what the blocked command wraps."""
    results = []
    project = make_project(root, "drifted")
    drift_the_index(project)

    argv = [
        "--framework-root", str(project / ".eif" / "runtime"),
        "--instance-path", str(project),
    ]
    strict = io.StringIO()
    with contextlib.redirect_stdout(strict):
        strict_rc = verify.main(argv)
    results.append(check(
        "a drifted knowledge index still fails the ordinary verification run",
        strict_rc == 1 and "FAIL knowledge index drift" in strict.getvalue(),
        strict.getvalue()[-400:],
    ))

    deferred = io.StringIO()
    with contextlib.redirect_stdout(deferred):
        deferred_rc = verify.main([*argv, "--pre-upgrade"])
    text = deferred.getvalue()
    results.append(check(
        "--pre-upgrade reports the same drift as a note and does not fail",
        deferred_rc == 0 and "note knowledge index drift" in text,
        text[-400:],
    ))
    results.append(check(
        "--pre-upgrade still fails on anything outside the regenerated set",
        "bundle file hashes" in text and "config schema" in text,
        "the deferred run skipped checks it was never meant to skip",
    ))
    return results


def check_upgrade_repairs_index_drift(root: Path) -> list[tuple[bool, str]]:
    """End to end: the state that blocked the upgrade is now repaired by it."""
    results = []
    project = make_project(root, "repairable")
    drift_the_index(project)
    results.append(check("the fixture is genuinely drifted", not index_matches_lock(project)))

    commit_all(project, "hand-regenerate the index")
    rc = cli.main(["upgrade", "--instance-path", str(project)])
    results.append(check("upgrade runs instead of refusing", rc == 0))
    results.append(check(
        "upgrade regenerated the index and the hash that records it",
        index_matches_lock(project),
    ))
    return results


def check_workspace_runtime_pending_is_precise(root: Path) -> list[tuple[bool, str]]:
    """Only a wholly absent workspace runtime counts as "not materialized on
    this machine yet". A present but drifted one is a real failure and has to
    stay one, or this fix would turn a safeguard into a silent pass."""
    results = []
    project = make_project(root, "precision")
    results.append(check(
        "a project with no workspace lock is not pending",
        not upgrade._workspace_runtime_pending(project),
    ))

    (project / ".eif" / "workspace.lock.yaml").write_bytes(b"schema_version: 1\n")
    results.append(check(
        "a workspace member with no local runtime is pending",
        upgrade._workspace_runtime_pending(project),
    ))

    (project / ".eif" / "workspace-runtime").mkdir()
    results.append(check(
        "a workspace member whose runtime exists is never pending, however broken it is",
        not upgrade._workspace_runtime_pending(project),
    ))
    return results


def check_fresh_clone_upgrade_succeeds(root: Path) -> list[tuple[bool, str]]:
    """The reported symptom: on a fresh clone of a connected project the
    framework axis succeeded, the tree stayed clean, and the command still
    exited 1 telling the operator not to commit changes that did not exist."""
    results = []
    project = make_project(root, "member")
    (project / ".eif" / "workspace.lock.yaml").write_bytes(b"schema_version: 1\n")
    commit_all(project, "join a workspace")

    captured = io.StringIO()
    with contextlib.redirect_stdout(captured):
        rc = cli.main(["upgrade", "--instance-path", str(project)])
    text = captured.getvalue()
    results.append(check(
        "upgrading a workspace member with no local workspace runtime succeeds",
        rc == 0,
        text[-600:],
    ))
    results.append(check(
        "it says the workspace axis is unchecked here and names the command that fixes it",
        "eifctl projects upgrade --apply" in text and "fresh clone" in text,
        text[-600:],
    ))
    results.append(check(
        "it does not tell the operator to revert anything",
        "do not commit" not in text.lower(),
        text[-600:],
    ))
    git(project, "update-index", "--refresh")
    dirty = git(project, "status", "--porcelain").stdout.strip()
    results.append(check("the tree it reported on is in fact clean", not dirty, dirty))
    return results


def main() -> int:
    results: list[tuple[bool, str]] = []
    # This suite runs against the working checkout, which is dirty whenever a
    # contributor is mid-change. Provenance dirtiness is a separate contract
    # covered by test_init.py.
    real_init_run = init_cmd.run
    patched = lambda argv: real_init_run([*argv, "--allow-dirty"])  # noqa: E731
    init_cmd.run = patched  # type: ignore[assignment]
    cli.COMMANDS["init"] = patched
    try:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            results += check_pre_upgrade_defers_regenerated_state(root)
            results += check_upgrade_repairs_index_drift(root)
            results += check_workspace_runtime_pending_is_precise(root)
            results += check_fresh_clone_upgrade_succeeds(root)
    finally:
        init_cmd.run = real_init_run  # type: ignore[assignment]
        cli.COMMANDS["init"] = real_init_run

    for _, line in results:
        print(line)
    failed = [line for ok, line in results if not ok]
    passed = len(results) - len(failed)
    # run_all.py parses this exact line to build the release inventory. Without
    # it the suite still runs and still fails the run on a real failure, but
    # its checks are counted as `unknown` and `--json` mode exits 1.
    print(f"EIF-RESULT: passed={passed} total={len(results)}")
    print(f"\ntest_upgrade_guards: {passed}/{len(results)} checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
