#!/usr/bin/env python3
"""Positive/negative fixture tests for eif_validate_frontmatter.py.

Every fixture named `positive_*` must pass (exit 0); every fixture named
`negative_*` must fail (exit 1). This is what "confirm every relevant gate
fails on bad input" means made concrete and automated, not just asserted
in prose.

Usage:
    python scripts/tests/test_validate.py
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "eif_validate_frontmatter.py"
FIXTURES = Path(__file__).resolve().parent / "fixtures"


def run(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, encoding="utf-8",
    )


def main() -> int:
    failures = []
    extra_checks = 0

    # --- frontmatter fixtures: each file validated individually ---
    fm_dir = FIXTURES / "frontmatter"
    fm_files = sorted(fm_dir.glob("*.md"))
    if not fm_files:
        print("no frontmatter fixtures found", file=sys.stderr)
        return 1

    for f in fm_files:
        rel = f.relative_to(REPO_ROOT)
        proc = run(["--framework-root", str(REPO_ROOT), "--instance-root", str(REPO_ROOT), str(rel)])
        expect_pass = f.name.startswith("positive_")
        expect_fail = f.name.startswith("negative_")
        if not (expect_pass or expect_fail):
            failures.append(f"fixture {f.name} doesn't start with positive_/negative_ - can't tell what to expect")
            continue
        ok = (proc.returncode == 0) if expect_pass else (proc.returncode != 0)
        status = "PASS" if ok else "FAIL"
        print(f"{status} {f.name} (exit={proc.returncode}, expected {'0' if expect_pass else 'nonzero'})")
        if not ok:
            failures.append(f"{f.name}: expected {'success' if expect_pass else 'failure'}, got exit {proc.returncode}\n{proc.stdout}\n{proc.stderr}")

    # --- config fixtures ---
    cfg_dir = FIXTURES / "config"
    cfg_files = sorted(cfg_dir.glob("*.yaml"))
    for f in cfg_files:
        proc = run(["--framework-root", str(REPO_ROOT), "--config", str(f)])
        expect_pass = f.name.startswith("positive")
        expect_fail = f.name.startswith("negative")
        if not (expect_pass or expect_fail):
            failures.append(f"fixture {f.name} doesn't start with positive/negative - can't tell what to expect")
            continue
        ok = (proc.returncode == 0) if expect_pass else (proc.returncode != 0)
        status = "PASS" if ok else "FAIL"
        print(f"{status} {f.name} (exit={proc.returncode}, expected {'0' if expect_pass else 'nonzero'})")
        if not ok:
            failures.append(f"{f.name}: expected {'success' if expect_pass else 'failure'}, got exit {proc.returncode}\n{proc.stdout}\n{proc.stderr}")

    # --- real project layout regression: ** must match root and nested
    # artifacts, while the exact EIF-generated index is navigation rather
    # than a frontmatter-bearing artifact. This is the shape the first
    # This reproduces the flat-plus-nested layout exposed by the first
    # private dogfood instance.
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        knowledge = root / "knowledge"
        nested = knowledge / "facts"
        nested.mkdir(parents=True)
        valid = (
            "---\ntype: fact\nstatus: validated\nscope: project\n"
            "evidence: OBSERVED\nsource: code\ncreated: 2026-07-28\n---\n\n# Fact\n"
        )
        (knowledge / "root-fact.md").write_text(valid, encoding="utf-8")
        (nested / "nested-fact.md").write_text(valid, encoding="utf-8")
        (knowledge / "index.md").write_text(
            "<!-- Auto-generated by scripts/eif_generate_index.py. Do not edit by hand. -->\n\n# Knowledge Index\n",
            encoding="utf-8",
        )
        proc = run([
            "--framework-root", str(REPO_ROOT),
            "--instance-root", str(root),
            "knowledge/**/*.md",
        ])
        ok = proc.returncode == 0 and "2 file(s), 0 error(s)" in proc.stdout
        print(f"{'PASS' if ok else 'FAIL'} recursive flat+nested knowledge layout skips only managed index")
        extra_checks += 1
        if not ok:
            failures.append(f"recursive flat+nested layout should pass exactly two artifacts\n{proc.stdout}\n{proc.stderr}")

        (knowledge / "index.md").write_text("# Hand-authored index without frontmatter\n", encoding="utf-8")
        proc = run([
            "--framework-root", str(REPO_ROOT),
            "--instance-root", str(root),
            "knowledge/**/*.md",
        ])
        ok = proc.returncode != 0 and "index.md: no frontmatter block found" in proc.stdout
        print(f"{'PASS' if ok else 'FAIL'} hand-authored frontmatter-less index is not silently skipped")
        extra_checks += 1
        if not ok:
            failures.append(f"hand-authored index should fail validation\n{proc.stdout}\n{proc.stderr}")

    total = len(fm_files) + len(cfg_files) + extra_checks
    print(f"EIF-RESULT: passed={total - len(failures)} total={total}")
    print(f"\ntest_validate: {total - len(failures)}/{total} fixture(s) behaved as expected")
    if failures:
        print("\nFailures:")
        for f in failures:
            print(f"- {f}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
