#!/usr/bin/env python3
"""Generate vendor-docs routing guidance and per-adapter MCP config templates.

Mirrors scripts/eif_generate_rtk_guidance.py: this reads a committed policy
source and writes deterministic artifacts under
integrations/vendor-docs/generated/. It never touches user-level
configuration - see the module note below.

WHY THIS DOES NOT INSTALL ANYTHING
----------------------------------
An MCP server for a vendor-documentation provider is configured at the
USER level (the agent's own config file in the user's home directory), not
inside a project instance. EIF's ratified boundary is that it generates
project-local guidance and never mutates user-level configuration, for the
same reason it does not install agent hooks: a framework that silently
edits files outside the repository it was pointed at is not auditable by
the person adopting it.

So this generator emits a REVIEWABLE TEMPLATE per adapter. The owner reads
it, supplies their own provider command and credentials, and installs it
themselves. Every generated file carries installed=false and
user_config_mutated_by_generator=false so that state is machine-checkable,
not merely promised in prose.

Usage:
    python scripts/eif_generate_vendor_docs_guidance.py [--check]

--check regenerates in memory and fails if the committed artifacts differ,
which is what the test suite uses to catch drift.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INTEGRATION_DIR = REPO_ROOT / "integrations" / "vendor-docs"
POLICY_PATH = INTEGRATION_DIR / "usage-policy.json"
MANIFEST_PATH = INTEGRATION_DIR / "manifest.json"
GENERATED_DIR = INTEGRATION_DIR / "generated"

# Where each adapter's MCP configuration actually lives, and in what format.
# Paths are written as ~-relative on purpose: an absolute path from one
# machine must never end up in this public repository.
ADAPTER_TARGETS = {
    "claude-code": {
        "config_path": "~/.claude.json",
        "format": "json",
        "config_key": "mcpServers",
    },
    "codex": {
        "config_path": "~/.codex/config.toml",
        "format": "toml",
        "config_key": "mcp_servers",
    },
    "cursor": {
        "config_path": "~/.cursor/mcp.json",
        "format": "json",
        "config_key": "mcpServers",
    },
    "hermes": {
        "config_path": "~/.hermes/config.json",
        "format": "json",
        "config_key": "mcpServers",
    },
}

# Deliberately NOT a hardcoded provider command. EIF has not verified any
# specific provider's invocation against that provider's primary source, and
# asserting one from recall is exactly the failure this framework documents
# about itself. The owner fills this in from their provider's own docs.
OWNER_SUPPLIED = "<owner-supplied: see your provider's own installation docs>"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build_mcp_template(adapter: str, target: dict, provider_id: str) -> dict:
    return {
        "schema_version": 1,
        "adapter": adapter,
        "integration": "vendor-docs",
        "provider": provider_id,
        "transport": "mcp",
        "config_path": target["config_path"],
        "config_key": target["config_key"],
        "config_format": target["format"],
        "server_entry": {
            "command": OWNER_SUPPLIED,
            "args": [],
            "env": {},
        },
        "installed": False,
        "template_only": True,
        "safety": {
            "user_config_mutated_by_generator": False,
            "active_install_requires_owner_review": True,
            "credentials_in_generated_artifact": False,
            "query_text_leaves_machine": True,
        },
        "review_before_install": [
            "Supply the provider command from the provider's own documentation, not from recall.",
            "Keep credentials in the agent's own config or environment, never in this repository.",
            "Confirm the provider's data boundary matches integrations.vendor_docs.data_boundary in .eif/config.yaml.",
            "Set a non-zero cost_cap_usd before enabling a quota-bearing provider.",
        ],
    }


def build_instructions(policy: dict, manifest: dict) -> str:
    provider_ids = ", ".join(p["id"] for p in manifest["providers"])
    lines: list[str] = [
        "# Vendor-docs routing instructions",
        "",
        "<!-- Generated by scripts/eif_generate_vendor_docs_guidance.py from "
        "usage-policy.json. Do not edit by hand. -->",
        "",
        f"Policy version: `{policy['policy_version']}`. "
        f"Declared providers: `{provider_ids}`.",
        "",
        "Current vendor documentation outranks recall about a dependency's "
        "surface. It does not outrank an observation of what the code does.",
        "",
        "## Use a vendor-docs lookup when",
        "",
    ]
    for entry in policy["use_when"]:
        lines.append(f"- **{entry['id']}**: {entry['trigger']}")
        lines.append(f"  {entry['rationale']}")
    lines.append("")
    lines.append("## Do not use it when")
    lines.append("")
    for entry in policy["do_not_use_when"]:
        lines.append(f"- **{entry['id']}**: {entry['trigger']}")
        lines.append(f"  {entry['rationale']}")
    lines.append("")
    lines.append("## Boundaries")
    lines.append("")
    for boundary in policy["boundaries"]:
        lines.append(f"- {boundary}")
    lines.append("")
    lines.append(
        "The framework never installs MCP servers or mutates user-level "
        "configuration. Apply any generated template manually after review."
    )
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[Path, str]:
    policy = load_json(POLICY_PATH)
    manifest = load_json(MANIFEST_PATH)
    provider_id = manifest["providers"][0]["id"]

    artifacts: dict[Path, str] = {
        GENERATED_DIR / "vendor-docs-instructions.md": build_instructions(policy, manifest)
    }
    for adapter, target in sorted(ADAPTER_TARGETS.items()):
        payload = build_mcp_template(adapter, target, provider_id)
        artifacts[GENERATED_DIR / "mcp" / f"{adapter}.json"] = (
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
        )
    return artifacts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed artifacts differ from a fresh generation",
    )
    args = parser.parse_args()

    artifacts = generate()

    if args.check:
        drift = []
        for path, content in artifacts.items():
            if not path.exists():
                drift.append(f"missing: {path.relative_to(REPO_ROOT)}")
            elif path.read_text(encoding="utf-8") != content:
                drift.append(f"stale: {path.relative_to(REPO_ROOT)}")
        for item in drift:
            print(f"FAIL {item}")
        if drift:
            print(
                "[vendor-docs] regenerate with "
                "python scripts/eif_generate_vendor_docs_guidance.py"
            )
            return 1
        print(f"[vendor-docs] ok: {len(artifacts)} generated artifacts match")
        return 0

    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
