#!/usr/bin/env python3
"""Adoption preflight for eif_init.py: detect pre-existing project state
BEFORE any write, and classify each observation OK / WARN / STOP.

This exists because a naive bootstrap onto an EXISTING repository (as
opposed to a genuinely empty greenfield one) can silently do the wrong
thing even when every individual write is "safe" in isolation:
appending a block that declares itself the project's authority into a
CLAUDE.md that already has its own governance is technically a clean
marker-safe append (scripts/eif_markers.py has no complaint) and still
the wrong outcome - a second, competing authority statement the project
owner never asked for. Same reasoning extends to a knowledge index:
silently creating or overwriting one in a project that already manages
its own knowledge is the same class of mistake in a different file.

A STOP here means eif_init.py must not write ANYTHING - not "write
everything except the risky part." Resolving a STOP means the caller
makes an explicit decision and re-runs; it is never auto-resolved by
picking a default. --dry-run and a real run call the exact same function
here, so the printed plan cannot drift from what is actually enforced
(independent-review finding: the original version's index handling was
invisible to --dry-run entirely).

Usage (library only - eif_init.py is the caller; no standalone CLI here,
matching eif_markers.py's shape):
    from eif_preflight import run_preflight
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from eif_markers import find_managed_block, MarkerConflict

# Below this many stripped characters, existing entrypoint content is not
# treated as "governance" - a near-empty or placeholder file is not worth
# a STOP. Chosen well below any real rules section (compare: the shortest
# real per-project CLAUDE.md content seen in framework testing is several
# hundred characters).
GOVERNANCE_CONTENT_THRESHOLD = 40

# Written at the very start of every EIF-generated knowledge index -
# scripts/eif_generate_index.py's own render() output. Used here purely
# as an ownership signal: a file at knowledge.index_path that starts with
# this exact text was generated by EIF and is therefore safe to
# regenerate; anything else at that path is presumed project-owned and
# must never be silently overwritten. Kept as a plain string constant
# (not imported from eif_generate_index) so this module has no import-
# time dependency on it - only string equality matters here.
MANAGED_INDEX_MARKER = "<!-- Auto-generated by scripts/eif_generate_index.py. Do not edit by hand. -->"


@dataclass
class PreflightCheck:
    level: str  # "OK" | "WARN" | "STOP"
    message: str


@dataclass
class PreflightReport:
    checks: list[PreflightCheck] = field(default_factory=list)
    # True when the entrypoint file already holds substantial project
    # content with no EIF markers yet - i.e. this instance is being created
    # ON TOP OF a repository that already had its own GOVERNANCE. This is a
    # governance-detection signal only. It is deliberately NOT the source of
    # the historical migration_status any more: repository ORIGIN (was this
    # an empty repo or a pre-existing one?) is a different question - an
    # existing code repo with no CLAUDE.md has no governance here yet but is
    # still historically `adopted` - and is detected separately by
    # eif_init.detect_repository_origin(). Keeping the two apart is the fix
    # for an existing repo without a CLAUDE.md being mis-recorded greenfield.
    detected_pre_existing_entrypoint: bool = False

    def add(self, level: str, message: str) -> None:
        self.checks.append(PreflightCheck(level, message))

    @property
    def has_stop(self) -> bool:
        return any(c.level == "STOP" for c in self.checks)

    def render(self, prefix: str = "") -> list[str]:
        return [f"{prefix}{c.level:<4} {c.message}" for c in self.checks]


def determine_index_action(
    *,
    knowledge_root_path: Path,
    knowledge_index_path: Path,
    knowledge_root_configured: str,
    knowledge_index_path_configured: str,
    knowledge_managed: bool,
) -> tuple[str, str]:
    """Returns (action, message). action is one of:
      skip   - nothing will be written (management off, or root missing)
      create - a new index file will be written
      update - an existing EIF-owned index will be regenerated
      stop   - refuses to proceed (existing non-EIF index, or missing
               parent directory)
    Read-only - does not write anything, including .next files. Called by
    both --dry-run (to report) and a real run (to decide what to stage) -
    same function, so the two cannot disagree."""
    if not knowledge_managed:
        return "skip", (
            "knowledge index management is not enabled for this instance "
            "(coexist mode defaults to off - pass --manage-knowledge-index "
            "to opt in explicitly)"
        )
    if not knowledge_root_path.is_dir():
        return "skip", f"knowledge root '{knowledge_root_configured}' does not exist yet"
    if not knowledge_index_path.parent.is_dir():
        return "stop", (
            f"parent directory of knowledge.index_path "
            f"('{knowledge_index_path.parent}') does not exist - eif_init.py "
            f"does not create new directories for this; create it first or "
            f"point knowledge.index_path at an existing directory"
        )
    if not knowledge_index_path.exists():
        return "create", f"would create a new EIF-managed knowledge index at '{knowledge_index_path_configured}'"
    try:
        existing_text = knowledge_index_path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return "stop", f"could not read existing file at '{knowledge_index_path_configured}': {e}"
    if existing_text.startswith(MANAGED_INDEX_MARKER):
        return "update", f"would regenerate the existing EIF-managed knowledge index at '{knowledge_index_path_configured}'"
    return "stop", (
        f"a file already exists at knowledge.index_path "
        f"('{knowledge_index_path_configured}') without EIF's ownership marker - "
        f"refusing to overwrite a project-owned file. Move or rename it "
        f"first if you want EIF to manage a knowledge index at this path."
    )


def run_preflight(
    *,
    mode: str,
    entrypoint_name: str,
    entry_strategy: str,
    existing_entry_text: str | None,
    existing_gitignore_text: str | None,
    knowledge_root_path: Path,
    knowledge_root_configured: str,
    knowledge_index_path: Path,
    knowledge_index_path_configured: str,
    knowledge_managed: bool,
    adoption_basis: str,
    begin_marker: str,
    end_marker: str,
    gitignore_begin: str,
    gitignore_end: str,
    governance_surfaces: list[str] | None = None,
) -> PreflightReport:
    """Build the structured OK/WARN/STOP report. Read-only - never writes.

    `adoption_basis` is resolved by the caller (eif_init.py main()) from
    persisted config + this run's flags, BEFORE calling here - one of:
      "explicit_coexist"            - --adoption-mode coexist this run
      "explicit_greenfield_override"- --adoption-mode greenfield this run
                                       (an informed override, not a default)
      "persisted_coexist"           - existing config already says coexist
                                       (upgrade/reconfigure, no flag needed)
      "undecided"                   - none of the above: a silent default,
                                       not a real decision - always STOPs
                                       when substantial ungoverned content
                                       exists, regardless of mode
    Independent-review fix: the previous version only ever STOPped when
    mode == "init" - an upgrade or reconfigure run that somehow reached
    this state (e.g. markers manually deleted after a prior install) fell
    through to a WARN instead. Governed uniformly by adoption_basis now,
    not by mode.

    `entry_strategy` ("marker-merge" | "full-regen") branches the existing-
    entrypoint-content check: a "shared"-ownership entrypoint (CLAUDE.md)
    may legitimately already hold real project content, so the response is
    adoption-mode-dependent (OK if coexist, WARN if an explicit greenfield
    override, STOP if undecided). A "full-regen"/exclusive entrypoint
    (Cursor's dedicated file) has NO legitimate "the project already put
    real content here" case - existing content without a valid EIF block
    always STOPs, regardless of adoption mode or content size, and the
    message never claims the generated content will "defer to" what's
    there, since full-regen replaces the whole file rather than preserving
    anything outside markers.
    """
    report = PreflightReport()

    # --- Existing governance in the entrypoint file ---
    has_existing_markers = False
    if existing_entry_text is not None:
        try:
            has_existing_markers = find_managed_block(existing_entry_text, begin_marker, end_marker) is not None
        except MarkerConflict:
            has_existing_markers = True  # surfaced below as its own STOP

        if entry_strategy == "full-regen":
            if has_existing_markers:
                report.add("OK", f"{entrypoint_name}: existing EIF-managed block found, will refresh in place.")
            else:
                report.detected_pre_existing_entrypoint = True
                report.add(
                    "STOP",
                    f"{entrypoint_name} exists but has no EIF ownership markers. This path is "
                    f"exclusively EIF-owned by contract - nothing else has a legitimate reason "
                    f"to be there - so its ownership must be proven (a single well-formed EIF "
                    f"block) before it can be regenerated. Refusing to overwrite unknown content, "
                    f"regardless of adoption mode or file size. Move or rename the existing file "
                    f"first if EIF should manage a fresh one at this path.",
                )
        else:
            substantial = len(existing_entry_text.strip()) >= GOVERNANCE_CONTENT_THRESHOLD
            if substantial and not has_existing_markers:
                report.detected_pre_existing_entrypoint = True
                if adoption_basis in ("explicit_coexist", "persisted_coexist"):
                    report.add(
                        "OK",
                        f"{entrypoint_name} has existing content; adoption mode is coexist "
                        f"({adoption_basis}) - the generated block will defer to it, not compete with it.",
                    )
                elif adoption_basis == "explicit_greenfield_override":
                    report.add(
                        "WARN",
                        f"{entrypoint_name} has existing content, but --adoption-mode greenfield "
                        f"was explicitly passed this run - proceeding as an informed override, not a default.",
                    )
                else:
                    report.add(
                        "STOP",
                        f"{entrypoint_name} already has substantial content and no EIF markers yet, "
                        f"and there is no adoption-mode decision on record (mode={mode}). Pass "
                        f"--adoption-mode coexist (the generated block will not claim sole authority "
                        f"and will defer to your existing rules) or --adoption-mode greenfield "
                        f"(explicit override) before proceeding - refusing to append a competing "
                        f"authority block silently.",
                    )
            elif substantial and has_existing_markers:
                report.add("OK", f"{entrypoint_name}: existing EIF-managed block found, will refresh in place.")
            elif not substantial:
                report.add("OK", f"{entrypoint_name}: no substantial pre-existing content, safe to create/append.")
    else:
        report.add("OK", f"{entrypoint_name}: does not exist yet, will be created.")

    # --- Other governance surfaces this adapter's own contract reads
    # (sibling project-owned rule files, legacy formats, other shared
    # signals) - distinct from the entrypoint file itself. Detected
    # read-only by eif_adapters.discover_governance_surfaces(); reported
    # here by exact relative path so dry-run and a real run see the same
    # list. Coexist preserves them untouched; undecided STOPs; explicit
    # greenfield override proceeds but still never touches them (enforced
    # by the caller, which is only ever supposed to write the adapter's own
    # entrypoint - these paths are never staged for writing anywhere).
    if governance_surfaces:
        surfaces_str = ", ".join(governance_surfaces)
        if adoption_basis in ("explicit_coexist", "persisted_coexist"):
            report.add(
                "OK",
                f"existing governance surface(s) detected and will be left untouched "
                f"(coexist, {adoption_basis}): {surfaces_str}",
            )
        elif adoption_basis == "explicit_greenfield_override":
            report.add(
                "WARN",
                f"existing governance surface(s) detected, but --adoption-mode greenfield "
                f"was explicitly passed this run - proceeding as an informed override; these "
                f"are still never written to: {surfaces_str}",
            )
        else:
            report.add(
                "STOP",
                f"existing governance surface(s) detected and there is no adoption-mode "
                f"decision on record (mode={mode}): {surfaces_str}. Pass --adoption-mode "
                f"coexist (these are preserved untouched either way) or --adoption-mode "
                f"greenfield (explicit override) before proceeding.",
            )

    # --- Malformed markers (surfaced here too, not only as eif_init's later hard failure) ---
    for label, text, begin, end in (
        (entrypoint_name, existing_entry_text, begin_marker, end_marker),
        (".gitignore", existing_gitignore_text, gitignore_begin, gitignore_end),
    ):
        if text is None:
            continue
        try:
            find_managed_block(text, begin, end)
        except MarkerConflict as e:
            report.add("STOP", f"{label}: malformed EIF markers, refusing to write - {e}")

    # --- Knowledge index (independent-review: must be visible to dry-run too) ---
    index_action, index_message = determine_index_action(
        knowledge_root_path=knowledge_root_path,
        knowledge_index_path=knowledge_index_path,
        knowledge_root_configured=knowledge_root_configured,
        knowledge_index_path_configured=knowledge_index_path_configured,
        knowledge_managed=knowledge_managed,
    )
    level = {"skip": "OK", "create": "OK", "update": "OK", "stop": "STOP"}[index_action]
    report.add(level, f"knowledge index: {index_message}")

    return report
