#!/usr/bin/env python3
"""Generate a knowledge index for an EIF project instance.

NEW-CORRECTION (see the private migration ledger, PACKET-2026-07-14-eif-
public-productization/04-MIGRATION-LEDGER-001): the private EI's equivalent
generator is PowerShell-only, which is not reproducible on a non-Windows
clean checkout. This is a from-scratch Python implementation of the same
concept (scan frontmatter, emit a table), not a port of the PowerShell
script's code.

Scans a directory for Markdown files with EIF frontmatter and writes a
single index table (type/status/scope/review_after) plus a short excerpt of
the first non-heading line of each file, for use by
scripts/eif_search_knowledge.py and for human browsing.

Malformed frontmatter does not crash the run - it's reported and excluded,
the same "fail loud, don't fail closed on a file the scan can't be sure
about" posture as scripts/eif_privacy_scan.py's fail-closed rule.

Usage:
    python scripts/eif_generate_index.py --knowledge-root PATH [--out PATH]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "eif-generate-index: PyYAML is required. Install with: "
        "pip install -r scripts/requirements.txt",
        file=sys.stderr,
    )
    raise SystemExit(1)

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)", re.S)


def extract(path: Path) -> tuple[dict, str] | None:
    text = path.read_text(encoding="utf-8", errors="ignore")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None
    if not isinstance(fm, dict):
        return None
    body = m.group(2)
    excerpt = ""
    for line in body.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("<!--"):
            excerpt = stripped[:80]
            break
    return fm, excerpt


def build_index(knowledge_root: Path) -> tuple[list[dict], list[Path]]:
    rows = []
    malformed = []
    for path in sorted(knowledge_root.rglob("*.md")):
        if path.name == "index.md":
            continue
        result = extract(path)
        if result is None:
            malformed.append(path)
            continue
        fm, excerpt = result
        rows.append(
            {
                "path": path.relative_to(knowledge_root).as_posix(),
                "type": fm.get("type", ""),
                "status": fm.get("status", ""),
                "scope": fm.get("scope", ""),
                "review_after": str(fm.get("review_after", "")),
                # Carried for lifecycle-aware retrieval (eif_search_knowledge):
                "evidence": fm.get("evidence", ""),
                "confidence": fm.get("confidence", ""),
                "source": fm.get("source", ""),
                "excerpt": excerpt,
            }
        )
    return rows, malformed


def render(rows: list[dict], malformed: list[Path], knowledge_root: Path) -> str:
    lines = [
        "<!-- Auto-generated by scripts/eif_generate_index.py. Do not edit by hand. -->",
        "",
        "# Knowledge Index",
        "",
        "| File | Type | Status | Scope | Review After | Excerpt |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['path']} | {row['type']} | {row['status']} | {row['scope']} | "
            f"{row['review_after']} | {row['excerpt']} |"
        )
    if malformed:
        lines.append("")
        lines.append("## Excluded (malformed frontmatter)")
        lines.append("")
        for path in malformed:
            lines.append(f"- {path.relative_to(knowledge_root).as_posix()}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--knowledge-root", required=True, help="Directory to scan for *.md knowledge artifacts")
    ap.add_argument("--out", default=None, help="Where to write index.md (default: <knowledge-root>/index.md)")
    args = ap.parse_args()

    knowledge_root = Path(args.knowledge_root).resolve()
    if not knowledge_root.is_dir():
        print(f"eif-generate-index: not a directory: {knowledge_root}", file=sys.stderr)
        return 1

    rows, malformed = build_index(knowledge_root)
    out_path = Path(args.out).resolve() if args.out else knowledge_root / "index.md"
    out_path.write_text(render(rows, malformed, knowledge_root), encoding="utf-8")

    print(f"eif-generate-index: {len(rows)} artifact(s), {len(malformed)} excluded, wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
