#!/usr/bin/env python3
"""Generate compact public RTK routing guidance from command-registry.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from jsonschema import Draft202012Validator


FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = FRAMEWORK_ROOT / "integrations" / "rtk" / "command-registry.json"
SCHEMA_PATH = FRAMEWORK_ROOT / "core" / "schemas" / "rtk-command-registry.schema.json"
OUTPUT_PATH = FRAMEWORK_ROOT / "integrations" / "rtk" / "generated-instructions.md"


def render(registry: dict) -> str:
    lines = [
        "# RTK routing instructions",
        "",
        "<!-- Generated by scripts/eif_generate_rtk_guidance.py from command-registry.json. Do not edit by hand. -->",
        "",
        f"Registry version: `{registry['registry_version']}`. Tested RTK: `{', '.join(registry['tested_rtk_versions'])}`.",
        "",
        "Correctness precedes compression. A route is savings-eligible only when its canary passes.",
        "",
    ]
    for route in registry["routes"]:
        eligibility = "savings-eligible" if route["savings_eligible"] else "zero savings"
        lines.append(f"- `{route['id']}`: `{route['canonical_form']}` - {eligibility}; argv: {route['argv_policy']}.")
        if route.get("note"):
            lines.append(f"  {route['note']}")
    lines.extend([
        "",
        "The framework never installs hooks or mutates user-level configuration. Apply any generated guidance manually after review.",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    errors = list(Draft202012Validator(schema).iter_errors(registry))
    if errors:
        print(f"eif-generate-rtk-guidance: registry invalid ({len(errors)} error(s))")
        return 1
    expected = render(registry)
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print("eif-generate-rtk-guidance: generated instructions are stale")
            return 1
        print("eif-generate-rtk-guidance: generated instructions are current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print("eif-generate-rtk-guidance: wrote integrations/rtk/generated-instructions.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
